version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Running tests...


  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  - index.html
