version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g prettier
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - prettier --write "index.html"
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
